# Generated by Django 4.2.11 on 2024-03-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название игры')),
                ('developer', models.CharField(max_length=70, verbose_name='Разработчик игры')),
                ('release_date', models.DateTimeField(verbose_name='Дата выхода игры')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('avg_score', models.FloatField(verbose_name='Средний рейтинг игры')),
                ('image', models.ImageField(default='There is no image', upload_to='games/static/games/img/', verbose_name='Изображение игры')),
                ('genres', models.ManyToManyField(related_name='games', to='games.genre')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
